// <auto-generated />
namespace FantasyFootballPlayoffs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createnullablefieldsinstatstabl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createnullablefieldsinstatstabl));
        
        string IMigrationMetadata.Id
        {
            get { return "201712120006176_create nullable fields in stats tabl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
