// <auto-generated />
namespace FantasyFootballPlayoffs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changenameofdraftpickinformation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changenameofdraftpickinformation));
        
        string IMigrationMetadata.Id
        {
            get { return "201712311933055_change name of draft pick information"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
