namespace FantasyFootballPlayoffs.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class reworkedstatstables : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.fantasy_League", "sport_sport_PK", "dbo.sports");
            DropForeignKey("dbo.fantasy_Roster", "player_player_PK", "dbo.players");
            DropForeignKey("dbo.fantasy_Roster", "sport_sport_PK", "dbo.sports");
            DropForeignKey("dbo.gameStats", "playerid_player_PK", "dbo.players");
            DropForeignKey("dbo.gameStats", "gameid_game_PK", "dbo.games");
            DropForeignKey("dbo.teams", "locationid_location_PK", "dbo.locations");
            DropForeignKey("dbo.games", "sportid_sport_PK", "dbo.sports");
            DropForeignKey("dbo.teams", "sportid_sport_PK", "dbo.sports");
            DropForeignKey("dbo.gameStats", "statisticalCategoryid_statisticalCategory_PK", "dbo.statisticalCategories");
            DropForeignKey("dbo.players", "playerPositionid_playerPosition_PK", "dbo.playerPositions");
            DropIndex("dbo.fantasy_League", new[] { "sport_sport_PK" });
            DropIndex("dbo.fantasy_Roster", new[] { "player_player_PK" });
            DropIndex("dbo.fantasy_Roster", new[] { "sport_sport_PK" });
            DropColumn("dbo.fantasy_Roster", "playerId");
            DropColumn("dbo.fantasy_Roster", "sportId");
            RenameColumn(table: "dbo.fantasy_Roster", name: "player_player_PK", newName: "playerId");
            RenameColumn(table: "dbo.fantasy_Roster", name: "sport_sport_PK", newName: "sportId");
            RenameColumn(table: "dbo.gameStats", name: "gameid_game_PK", newName: "gameid_Id");
            RenameColumn(table: "dbo.gameStats", name: "playerid_player_PK", newName: "playerid_Id");
            RenameColumn(table: "dbo.gameStats", name: "statisticalCategoryid_statisticalCategory_PK", newName: "statisticalCategoryid_Id");
            RenameColumn(table: "dbo.games", name: "sportid_sport_PK", newName: "sportid_Id");
            RenameColumn(table: "dbo.teams", name: "locationid_location_PK", newName: "locationid_Id");
            RenameColumn(table: "dbo.players", name: "teamid_team_PK", newName: "team_team_PK");
            RenameColumn(table: "dbo.teams", name: "sportid_sport_PK", newName: "sportid_Id");
            RenameColumn(table: "dbo.players", name: "playerPositionid_playerPosition_PK", newName: "playerPositionId");
            RenameIndex(table: "dbo.players", name: "IX_playerPositionid_playerPosition_PK", newName: "IX_playerPositionId");
            RenameIndex(table: "dbo.players", name: "IX_teamid_team_PK", newName: "IX_team_team_PK");
            RenameIndex(table: "dbo.teams", name: "IX_locationid_location_PK", newName: "IX_locationid_Id");
            RenameIndex(table: "dbo.teams", name: "IX_sportid_sport_PK", newName: "IX_sportid_Id");
            RenameIndex(table: "dbo.games", name: "IX_sportid_sport_PK", newName: "IX_sportid_Id");
            RenameIndex(table: "dbo.gameStats", name: "IX_gameid_game_PK", newName: "IX_gameid_Id");
            RenameIndex(table: "dbo.gameStats", name: "IX_playerid_player_PK", newName: "IX_playerid_Id");
            RenameIndex(table: "dbo.gameStats", name: "IX_statisticalCategoryid_statisticalCategory_PK", newName: "IX_statisticalCategoryid_Id");
            DropPrimaryKey("dbo.players");
            DropPrimaryKey("dbo.gameStats");
            DropPrimaryKey("dbo.games");
            DropPrimaryKey("dbo.locations");
            DropPrimaryKey("dbo.sports");
            DropPrimaryKey("dbo.statisticalCategories");
            DropPrimaryKey("dbo.playerPositions");
            AddColumn("dbo.players", "Id", c => c.Int(nullable: false, identity: false));
            AddColumn("dbo.players", "teamId", c => c.Int());
            AddColumn("dbo.gameStats", "Id", c => c.Int(nullable: false, identity: false));
            AddColumn("dbo.games", "Id", c => c.Int(nullable: false, identity: false));
            AddColumn("dbo.locations", "Id", c => c.Int(nullable: false, identity: false));
            AddColumn("dbo.sports", "Id", c => c.Int(nullable: false, identity: false));
            AddColumn("dbo.statisticalCategories", "Id", c => c.Int(nullable: false, identity: false));
            AddColumn("dbo.playerPositions", "Id", c => c.Int(nullable: false, identity: false));
            AlterColumn("dbo.fantasy_Roster", "playerId", c => c.Int(nullable: false));
            AlterColumn("dbo.fantasy_Roster", "sportId", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.players", "Id");
            AddPrimaryKey("dbo.gameStats", "Id");
            AddPrimaryKey("dbo.games", "Id");
            AddPrimaryKey("dbo.locations", "Id");
            AddPrimaryKey("dbo.sports", "Id");
            AddPrimaryKey("dbo.statisticalCategories", "Id");
            AddPrimaryKey("dbo.playerPositions", "Id");
            CreateIndex("dbo.fantasy_Roster", "playerId");
            CreateIndex("dbo.fantasy_Roster", "sportId");
            AddForeignKey("dbo.fantasy_Roster", "playerId", "dbo.players", "Id", cascadeDelete: true);
            AddForeignKey("dbo.fantasy_Roster", "sportId", "dbo.sports", "Id", cascadeDelete: true);
            AddForeignKey("dbo.gameStats", "playerid_Id", "dbo.players", "Id");
            AddForeignKey("dbo.gameStats", "gameid_Id", "dbo.games", "Id");
            AddForeignKey("dbo.teams", "locationid_Id", "dbo.locations", "Id");
            AddForeignKey("dbo.teams", "sportid_Id", "dbo.sports", "Id");
            AddForeignKey("dbo.games", "sportid_Id", "dbo.sports", "Id");
            AddForeignKey("dbo.gameStats", "statisticalCategoryid_Id", "dbo.statisticalCategories", "Id");
            AddForeignKey("dbo.players", "playerPositionId", "dbo.playerPositions", "Id");
            DropColumn("dbo.fantasy_League", "sport_sport_PK");
            DropColumn("dbo.players", "player_PK");
            DropColumn("dbo.gameStats", "gameStat_PK");
            DropColumn("dbo.games", "game_PK");
            DropColumn("dbo.locations", "location_PK");
            DropColumn("dbo.sports", "sport_PK");
            DropColumn("dbo.statisticalCategories", "statisticalCategory_PK");
            DropColumn("dbo.playerPositions", "playerPosition_PK");
        }
        
        public override void Down()
        {
            AddColumn("dbo.playerPositions", "playerPosition_PK", c => c.Int(nullable: false, identity: false));
            AddColumn("dbo.statisticalCategories", "statisticalCategory_PK", c => c.Int(nullable: false, identity: false));
            AddColumn("dbo.sports", "sport_PK", c => c.Int(nullable: false, identity: false));
            AddColumn("dbo.locations", "location_PK", c => c.Int(nullable: false, identity: false));
            AddColumn("dbo.games", "game_PK", c => c.Int(nullable: false, identity: false));
            AddColumn("dbo.gameStats", "gameStat_PK", c => c.Int(nullable: false, identity: false));
            AddColumn("dbo.players", "player_PK", c => c.Int(nullable: false, identity: false));
            AddColumn("dbo.fantasy_League", "sport_sport_PK", c => c.Int());
            DropForeignKey("dbo.players", "playerPositionId", "dbo.playerPositions");
            DropForeignKey("dbo.gameStats", "statisticalCategoryid_Id", "dbo.statisticalCategories");
            DropForeignKey("dbo.games", "sportid_Id", "dbo.sports");
            DropForeignKey("dbo.teams", "sportid_Id", "dbo.sports");
            DropForeignKey("dbo.teams", "locationid_Id", "dbo.locations");
            DropForeignKey("dbo.gameStats", "gameid_Id", "dbo.games");
            DropForeignKey("dbo.gameStats", "playerid_Id", "dbo.players");
            DropForeignKey("dbo.fantasy_Roster", "sportId", "dbo.sports");
            DropForeignKey("dbo.fantasy_Roster", "playerId", "dbo.players");
            DropIndex("dbo.fantasy_Roster", new[] { "sportId" });
            DropIndex("dbo.fantasy_Roster", new[] { "playerId" });
            DropPrimaryKey("dbo.playerPositions");
            DropPrimaryKey("dbo.statisticalCategories");
            DropPrimaryKey("dbo.sports");
            DropPrimaryKey("dbo.locations");
            DropPrimaryKey("dbo.games");
            DropPrimaryKey("dbo.gameStats");
            DropPrimaryKey("dbo.players");
            AlterColumn("dbo.fantasy_Roster", "sportId", c => c.Int());
            AlterColumn("dbo.fantasy_Roster", "playerId", c => c.Int());
            DropColumn("dbo.playerPositions", "Id");
            DropColumn("dbo.statisticalCategories", "Id");
            DropColumn("dbo.sports", "Id");
            DropColumn("dbo.locations", "Id");
            DropColumn("dbo.games", "Id");
            DropColumn("dbo.gameStats", "Id");
            DropColumn("dbo.players", "teamId");
            DropColumn("dbo.players", "Id");
            AddPrimaryKey("dbo.playerPositions", "playerPosition_PK");
            AddPrimaryKey("dbo.statisticalCategories", "statisticalCategory_PK");
            AddPrimaryKey("dbo.sports", "sport_PK");
            AddPrimaryKey("dbo.locations", "location_PK");
            AddPrimaryKey("dbo.games", "game_PK");
            AddPrimaryKey("dbo.gameStats", "gameStat_PK");
            AddPrimaryKey("dbo.players", "player_PK");
            RenameIndex(table: "dbo.gameStats", name: "IX_statisticalCategoryid_Id", newName: "IX_statisticalCategoryid_statisticalCategory_PK");
            RenameIndex(table: "dbo.gameStats", name: "IX_playerid_Id", newName: "IX_playerid_player_PK");
            RenameIndex(table: "dbo.gameStats", name: "IX_gameid_Id", newName: "IX_gameid_game_PK");
            RenameIndex(table: "dbo.games", name: "IX_sportid_Id", newName: "IX_sportid_sport_PK");
            RenameIndex(table: "dbo.teams", name: "IX_sportid_Id", newName: "IX_sportid_sport_PK");
            RenameIndex(table: "dbo.teams", name: "IX_locationid_Id", newName: "IX_locationid_location_PK");
            RenameIndex(table: "dbo.players", name: "IX_team_team_PK", newName: "IX_teamid_team_PK");
            RenameIndex(table: "dbo.players", name: "IX_playerPositionId", newName: "IX_playerPositionid_playerPosition_PK");
            RenameColumn(table: "dbo.players", name: "playerPositionId", newName: "playerPositionid_playerPosition_PK");
            RenameColumn(table: "dbo.teams", name: "sportid_Id", newName: "sportid_sport_PK");
            RenameColumn(table: "dbo.players", name: "team_team_PK", newName: "teamid_team_PK");
            RenameColumn(table: "dbo.teams", name: "locationid_Id", newName: "locationid_location_PK");
            RenameColumn(table: "dbo.games", name: "sportid_Id", newName: "sportid_sport_PK");
            RenameColumn(table: "dbo.gameStats", name: "statisticalCategoryid_Id", newName: "statisticalCategoryid_statisticalCategory_PK");
            RenameColumn(table: "dbo.gameStats", name: "playerid_Id", newName: "playerid_player_PK");
            RenameColumn(table: "dbo.gameStats", name: "gameid_Id", newName: "gameid_game_PK");
            RenameColumn(table: "dbo.fantasy_Roster", name: "sportId", newName: "sport_sport_PK");
            RenameColumn(table: "dbo.fantasy_Roster", name: "playerId", newName: "player_player_PK");
            AddColumn("dbo.fantasy_Roster", "sportId", c => c.Int(nullable: false));
            AddColumn("dbo.fantasy_Roster", "playerId", c => c.Int(nullable: false));
            CreateIndex("dbo.fantasy_Roster", "sport_sport_PK");
            CreateIndex("dbo.fantasy_Roster", "player_player_PK");
            CreateIndex("dbo.fantasy_League", "sport_sport_PK");
            AddForeignKey("dbo.players", "playerPositionid_playerPosition_PK", "dbo.playerPositions", "playerPosition_PK");
            AddForeignKey("dbo.gameStats", "statisticalCategoryid_statisticalCategory_PK", "dbo.statisticalCategories", "statisticalCategory_PK");
            AddForeignKey("dbo.teams", "sportid_sport_PK", "dbo.sports", "sport_PK");
            AddForeignKey("dbo.games", "sportid_sport_PK", "dbo.sports", "sport_PK");
            AddForeignKey("dbo.teams", "locationid_location_PK", "dbo.locations", "location_PK");
            AddForeignKey("dbo.gameStats", "gameid_game_PK", "dbo.games", "game_PK");
            AddForeignKey("dbo.gameStats", "playerid_player_PK", "dbo.players", "player_PK");
            AddForeignKey("dbo.fantasy_Roster", "sport_sport_PK", "dbo.sports", "sport_PK");
            AddForeignKey("dbo.fantasy_Roster", "player_player_PK", "dbo.players", "player_PK");
            AddForeignKey("dbo.fantasy_League", "sport_sport_PK", "dbo.sports", "sport_PK");
        }
    }
}
