// <auto-generated />
namespace FantasyFootballPlayoffs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedfantasyleagueandrostertablesforowner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedfantasyleagueandrostertablesforowner));
        
        string IMigrationMetadata.Id
        {
            get { return "201712161604081_updated fantasy league and roster tables for owner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
