// <auto-generated />
namespace FantasyFootballPlayoffs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixedFKstoalltables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedFKstoalltables));
        
        string IMigrationMetadata.Id
        {
            get { return "201711230430105_fixed FK's to all tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
