// <auto-generated />
namespace FantasyFootballPlayoffs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removerequirementforstattable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removerequirementforstattable));
        
        string IMigrationMetadata.Id
        {
            get { return "201712110611406_remove requirement for stat table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
