// <auto-generated />
namespace FantasyFootballPlayoffs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class moveduseridtofantasyleaguedetailstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moveduseridtofantasyleaguedetailstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201712280119498_moved userid to fantasy league details table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
