// <auto-generated />
namespace FantasyFootballPlayoffs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatefantasy_teamtablefordisplayname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatefantasy_teamtablefordisplayname));
        
        string IMigrationMetadata.Id
        {
            get { return "201712210907580_update fantasy_team table for display name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
