// <auto-generated />
namespace FantasyFootballPlayoffs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class calendarYearFKaddedtoleaguetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(calendarYearFKaddedtoleaguetable));
        
        string IMigrationMetadata.Id
        {
            get { return "201811210428596_calendarYear FK added to league table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
