// <auto-generated />
namespace FantasyFootballPlayoffs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class correctedfantatsyleaguedetailtoincludecalendaryearvscurrentyear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correctedfantatsyleaguedetailtoincludecalendaryearvscurrentyear));
        
        string IMigrationMetadata.Id
        {
            get { return "201811122010097_corrected fantatsy league detail to include calendar year vs current year"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
