// <auto-generated />
namespace FantasyFootballPlayoffs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class foreignkeyaddedtogamestable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foreignkeyaddedtogamestable));
        
        string IMigrationMetadata.Id
        {
            get { return "201811120511412_foreign key added to games table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
