USE [master]
GO

/****** Object:  Database [FantasyDatabase]    Script Date: 8/8/2018 3:38:18 PM ******/
CREATE DATABASE [FantasyDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FantasyDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\FantasyDatabase.mdf' , SIZE = 6336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FantasyDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\FantasyDatabase_log.ldf' , SIZE = 4736KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FantasyDatabase] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FantasyDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FantasyDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FantasyDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FantasyDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FantasyDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FantasyDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [FantasyDatabase] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [FantasyDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FantasyDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FantasyDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FantasyDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FantasyDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FantasyDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FantasyDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FantasyDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FantasyDatabase] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FantasyDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FantasyDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FantasyDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FantasyDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FantasyDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FantasyDatabase] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [FantasyDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FantasyDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FantasyDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [FantasyDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FantasyDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FantasyDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FantasyDatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [FantasyDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FantasyDatabase] SET  READ_WRITE 
GO

